"""upgrade_cithun_v1_4

迁移 ID: d6d9c2bbb3a2
父迁移: e5927f73764b
创建时间: 2026-06-10 17:02:16.483093

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlalchemy.exc

revision: str = "d6d9c2bbb3a2"
down_revision: str | Sequence[str] | None = "e5927f73764b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("nonebot_plugin_permission_aclentrymodel", schema=None) as batch_op:
            batch_op.drop_constraint(
                batch_op.f(
                    "fk_nonebot_plugin_permission_aclentrymodel_resource_id_nonebot_plugin_permission_resourcemodel"
                ),
                type_="foreignkey",
            )
    except sqlalchemy.exc.NoSuchTableError:
        pass
    op.drop_table("nonebot_plugin_permission_acldependencymodel", if_exists=True)
    op.drop_table("nonebot_plugin_permission_resourcemodel", if_exists=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "nonebot_plugin_permission_resourcemodel",
        sa.Column("id", sa.VARCHAR(length=256), nullable=False),
        sa.Column("name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("parent_id", sa.VARCHAR(length=256), nullable=True),
        sa.Column("inherit_mode", sa.VARCHAR(length=32), nullable=False),
        sa.Column("type", sa.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["nonebot_plugin_permission_resourcemodel.id"],
            name="fk_nonebot_plugin_permission_resourcemodel_parent_id_nonebot_plugin_permission_resourcemodel",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_nonebot_plugin_permission_resourcemodel"),
    )
    op.create_table(
        "nonebot_plugin_permission_acldependencymodel",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("acl_id", sa.INTEGER(), nullable=False),
        sa.Column("dep_subject_type", sa.VARCHAR(length=16), nullable=False),
        sa.Column("dep_subject_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("dep_resource_id", sa.VARCHAR(length=256), nullable=False),
        sa.Column("required_mask", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["acl_id"],
            ["nonebot_plugin_permission_aclentrymodel.id"],
            name=op.f("fk_nonebot_plugin_permission_acldependencymodel_acl_id_nonebot_plugin_permission_aclentrymodel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dep_resource_id"],
            ["nonebot_plugin_permission_resourcemodel.id"],
            name=op.f(
                "fk_nonebot_plugin_permission_acldependencymodel_dep_resource_id_nonebot_plugin_permission_resourcemodel"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_permission_acldependencymodel")),
    )

    with op.batch_alter_table("nonebot_plugin_permission_aclentrymodel", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_nonebot_plugin_permission_aclentrymodel_resource_id_nonebot_plugin_permission_resourcemodel"
            ),
            "nonebot_plugin_permission_resourcemodel",
            ["resource_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###
